version: '3'

tasks:
  tokens:
    sources:
      - ./utils/utopia/config.js
    generates:
      - src/design-tokens/text-sizes.json
      - src/design-tokens/spacing.json
      - src/design-tokens/viewports.json
    cmds:
      - node ./utils/utopia/src/index.js
