version: '3'

includes:
  format: ./format.yaml
  assets: ./assets.yaml
  setup: ./setup.yaml
    
tasks:
  default:
    deps:
      - task: clean
      - task: setup:install
    sources:
      - src/_includes/**/*.{njk}
      - src/css/**/*.css
      - src/design-tokens/**/*.json
    generates:
      - dist/index.html
      - dist/css/global.css
    cmds:
      - task: assets:create
      - task: format:src
      - pnpm eleventy
      - pnpm postcss src/css/global.css -o dist/css/global.css
#      - task: format:dist

  deploy:
    deps: [default]
    cmds:
      - pnpm gh-pages -d dist -b deploy
      
  clean:
    cmds:
      - rm -rf ./dist
      - mkdir ./dist
