version: '3'

tasks:
  site:
    sources:
      - src/_includes/**/*.{njk}
      - src/css/**/*.css
      - src/design-tokens/**/*.json
    generates:
      - dist/index.html
      - dist/css/global.css
    cmds:
      - pnpm eleventy
      - task build:postcss

  postcss:
    cmds:
      - pnpm postcss src/css/global.css -o dist/css/global.css
