version: '3'

includes:
  format: ./format.yaml
  assets: ./assets.yaml
  setup: ./setup.yaml
  
tasks:
  
  default:
    deps:
      - task: setup:install
      - task: postcss
      - task: serve
      - task: assets:create
    cmds:
      - task: format:src
      - task: dev:start

  serve:
    cmds:
      - pnpm eleventy --serve
    daemon: true
    silent: false

  postcss:
    cmds:
      - pnpm postcss src/css/global.css -o dist/css/global.css --watch
    daemon: true
    silent: false
